name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  FRONTEND_IMAGE: yourusername/guivcard-frontend
  BACKEND_IMAGE: yourusername/guivcard-backend

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from Git
        id: version
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  audit:
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python dependencies with pip-audit
        run: |
          docker run --rm -v $(pwd)/backend:/app -w /app python:3.11-slim sh -c " \
          python -m venv venv && \
          . venv/bin/activate && \
          pip install --upgrade pip setuptools && \
          pip install pip-audit && \
          pip-audit -r requirements.txt"

      - name: Check Node.js dependencies with npm audit
        run: |
          docker run --rm -v $(pwd)/frontend:/app -w /app node:18-alpine sh -c " \
          npm install && \
          npm audit"

  build-and-push-backend:
    runs-on: ubuntu-24.04
    needs: [setup, audit]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ needs.setup.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  build-and-push-frontend:
    runs-on: ubuntu-24.04
    needs: [setup, audit]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ needs.setup.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  update-dockerhub-description:
    runs-on: ubuntu-24.04
    needs: [build-and-push-backend, build-and-push-frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Backend Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.BACKEND_IMAGE }}
          readme-filepath: ./README.md
          short-description: "GuiVCard Backend - A modern CardDAV server with REST API"

      - name: Update Frontend Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.FRONTEND_IMAGE }}
          readme-filepath: ./README.md
          short-description: "GuiVCard Frontend - A modern CardDAV client web interface"